apiVersion: v2
name: bms
description: BMS (Apartment Manager) Helm Chart with PostgreSQL and Redis Subcharts
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://github.com/mohammadhosein-p/BMS-Frontend/blob/main/public/Logo.png

dependencies:
  - name: postgresql
    version: "16.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled

  - name: redis
    version: "20.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled