# TODO: review chart notes

# TODO: volume permission 1001:1001
postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: latest

  auth:
    database: app_db
    username: apt_user
    password: "apt_password_123"
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      storageClass: "manual"
      size: 500Mi
    service:
      ports:
        postgresql: 5432



# TODO: volume permission
redis:
  enabled: true
  architecture: standalone

  image:
    repository: bitnami/redis
    tag: latest

  auth:
    enabled: false

  master:
    extraFlags:
      - "--appendonly"
      - "yes"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

    persistence:
      enabled: true
      storageClass: "manual"
      size: 500Mi

    service:
      ports:
        redis: 6379


migration:
  enabled: true
  image: 
    repository: ghcr.io/mohammadhosein-p/apartment-manager-backend/apt_migration
    tag: latest
  driver: postgres
  command: up
  sslmode: disable


backend:
  replicaCount: 1

  image:
    repository: ghcr.io/farzaddm/apartment-manager-backend/apt_backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  config:
    appEnv: "development"
    appPort: "8080"
    dbSslMode: "disable"
    redisDb: "0"

  secrets:
    appSecretKey: "Apartment_Manager_Secret_2026_Unique"
    jwtAccessSecret: "Apartment_Manager_Access_Secret_2026_Unique"
    jwtAccessExpireMinutes: "15"
    jwtRefreshSecret: "Apartment_Manager_Refresh_Secret_2026_Unique"
    jwtRefreshExpireDays: "7"


frontend:
  replicaCount: 1

  image:
    repository: ghcr.io/mohammadhosein-p/aparmo-fr
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "300m"
      memory: "256Mi"

  config:
    baseUrl: "/api"

ingress:
  enabled: true
  className: nginx

  host: ""