
# TODO: Alloy can't read log file because lack of access to cluster files

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy

rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy

subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring

data:
  config.alloy: |
    logging {
      level = "info"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label  = "__host__"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
      }
    }

    local.file_match "pod_logs" {
      path_targets = discovery.relabel.pod_logs.output
    }

    loki.source.file "pod_logs" {
      targets    = local.file_match.pod_logs.targets
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: alloy

  template:
    metadata:
      labels:
        app: alloy

    spec:
      serviceAccountName: alloy

      containers:
        - name: alloy
          image: grafana/alloy:v1.10.2

          args:
            - "run"
            - "/etc/alloy/config.alloy"

          ports:
            - name: http
              containerPort: 12345

          volumeMounts:
            - name: config
              mountPath: /etc/alloy

            - name: varlog
              mountPath: /var/log
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: alloy-config

        - name: varlog
          hostPath:
            path: /var/log