apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deploy
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/backend-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/backend/backend-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
            - secretRef:
                name: {{ .Release.Name }}-backend-secret

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}