apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  APP_SECRET_KEY: {{ .Values.backend.secrets.appSecretKey | quote }}

  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}

  REDIS_PASSWORD: {{ .Values.redis.auth.password | default "" | quote }}

  JWT_ACCESS_SECRET: {{ .Values.backend.secrets.jwtAccessSecret | quote }}
  JWT_ACCESS_EXPIRE_MINUTES: {{ .Values.backend.secrets.jwtAccessExpireMinutes | quote }}

  JWT_REFRESH_SECRET: {{ .Values.backend.secrets.jwtRefreshSecret | quote }}
  JWT_REFRESH_EXPIRE_DAYS: {{ .Values.backend.secrets.jwtRefreshExpireDays | quote }}