apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deploy
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend/frontend-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-config

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

      restartPolicy: Always