
# TODO: volume permission 65534:65534
prometheus:
  server:
    enabled: true
    retention: "10d"

    ingress:
      enabled: false

    persistentVolume:
      enabled: true
      storageClass: "manual-prometheus"
      size: "500Mi"

    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  prometheus-node-exporter:
    enabled: true

  kube-state-metrics:
    enabled: true


  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false


grafana:
  enabled: true
  
  adminUser: admin
  adminPassword: "adminpassword"

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          url: http://monitoring-chart-prometheus-server.monitoring.svc.cluster.local:80
          access: proxy
          isDefault: true


ingress:
  enabled: true
  className: nginx
  host: ""