
# TODO: volume permission 65534:65534
prometheus:
  server:
    enabled: true
    retention: "10d"

    persistentVolume:
      enabled: true
      storageClass: "manual-prometheus"
      size: "500Mi"

    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  prometheus-node-exporter:
    enabled: true

  kube-state-metrics:
    enabled: true


  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false