apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-loki-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-loki
  hostPath:
    path: /data/{{ .Release.Name }}-loki
