repo:
  url: "https://github.com/mohammadhosein-p/BMS-devops.git"
  targetRevision: "HEAD"

  private: true
  username: "" # Github Username
  token: "" # Github Personal Access Token (PAT)

applications:
  - name: bms-app
    path: "helm/bms"
    destinationNamespace: default
    valueFiles:
      - values.yaml
  - name: monitoring-app
    path: "helm/monitoring"
    destinationNamespace: monitoring
    valueFiles:
      - values.yaml

argo-cd:
  global:
    domain: localhost
  server:
    extraArgs:
      - --insecure
  dex:
    enabled: false