apiVersion: v1
kind: Secret
metadata:
  name: github-bms-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.argo-cd.repository-info.url}}
  username: {{ .Values.argo-cd.repository-info.username }}
  password: {{ .Values.argo-cd.repository-info.PAT }}