apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-bms-repo
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: "https://github.com/mohammadhosein-p/BMS-devops"
  username: "mohammadhosein-p"
  # password: ""
  password: "YOUR_GITHUB_PAT_TOKEN_HERE"