apiVersion: v1
kind: PersistentVolume
metadata:
  name: migration-pv

spec:
  capacity:
    storage: 100Mi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: migration-manual

  hostPath:
    path: /data/migrations


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-pvc
  namespace: bms

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: migration-manual

  resources:
    requests:
      storage: 100Mi