apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-prometheus-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-prometheus
  hostPath:
    path: /data/{{ .Release.Name }}-prometheus
